final Map<String, String> countryCodes = {
  'Afghanistan': 'AFG',
  'Albania': 'ALB',
  'Algeria': 'DZA',
  'American Samoa': 'ASM',
  'Andorra': 'AND',
  'Angola': 'AGO',
  'Anguilla': 'AIA',
  'Antigua and Barbuda': 'ATG',
  'Argentina': 'ARG',
  'Armenia': 'ARM',
  'Aruba': 'ABW',
  'Australia': 'AUS',
  'Austria': 'AUT',
  'Azerbaijan': 'AZE',
  'Bahamas, The': 'BHS',
  'Bahrain': 'BHR',
  'Bangladesh': 'BGD',
  'Barbados': 'BRB',
  'Belarus': 'BLR',
  'Belgium': 'BEL',
  'Belgium-Luxembourg': 'BLX',
  'Belize': 'BLZ',
  'Benin': 'BEN',
  'Bermuda': 'BMU',
  'Bhutan': 'BTN',
  'Bolivia': 'BOL',
  'Bosnia and Herzegovina': 'BIH',
  'Botswana': 'BWA',
  'Br. Antr. Terr': 'BAT',
  'Brazil': 'BRA',
  'British Indian Ocean Ter.': 'IOT',
  'British Virgin Islands': 'VGB',
  'Brunei': 'BRN',
  'Bulgaria': 'BGR',
  'Burkina Faso': 'BFA',
  'Burundi': 'BDI',
  'Cambodia': 'KHM',
  'Cameroon': 'CMR',
  'Canada': 'CAN',
  'Cape Verde': 'CPV',
  'Cayman Islands': 'CYM',
  'Central African Republic': 'CAF',
  'Chad': 'TCD',
  'Chile': 'CHL',
  'China': 'CHN',
  'Christmas Island': 'CXR',
  'Cocos (Keeling) Islands': 'CCK',
  'Colombia': 'COL',
  'Comoros': 'COM',
  'Congo, Dem. Rep.': 'ZAR',
  'Congo, Rep.': 'COG',
  'Cook Islands': 'COK',
  'Costa Rica': 'CRI',
  'Cote d\'Ivoire': 'CIV',
  'Croatia': 'HRV',
  'Cuba': 'CUB',
  'Cyprus': 'CYP',
  'Czech Republic': 'CZE',
  'Denmark': 'DNK',
  'Djibouti': 'DJI',
  'Dominica': 'DMA',
  'Dominican Republic': 'DOM',
  'Ecuador': 'ECU',
  'Egypt, Arab Rep.': 'EGY',
  'El Salvador': 'SLV',
  'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI',
  'Estonia': 'EST',
  'Ethiopia': 'ETH',
  'European Union': 'EUN',
  'Faeroe Islands': 'FRO',
  'Falkland Island': 'FLK',
  'Fiji': 'FJI',
  'Finland': 'FIN',
  'France': 'FRA',
  'French Guiana': 'GUF',
  'French Polynesia': 'PYF',
  'Gabon': 'GAB',
  'Gambia, The': 'GMB',
  'Gaza Strip': 'GAZ',
  'Georgia': 'GEO',
  'Germany': 'DEU',
  'Ghana': 'GHA',
  'Gibraltar': 'GIB',
  'Greece': 'GRC',
  'Greenland': 'GRL',
  'Grenada': 'GRD',
  'Guadeloupe': 'GLP',
  'Guam': 'GUM',
  'Guatemala': 'GTM',
  'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB',
  'Guyana': 'GUY',
  'Haiti': 'HTI',
  'Holy See': 'VAT',
  'Honduras': 'HND',
  'Hong Kong, China': 'HKG',
  'Hungary': 'HUN',
  'Iceland': 'ISL',
  'India': 'IND',
  'Indonesia': 'IDN',
  'Iran, Islamic Rep.': 'IRN',
  'Iraq': 'IRQ',
  'Ireland': 'IRL',
  'Israel': 'ISR',
  'Italy': 'ITA',
  'Jamaica': 'JAM',
  'Japan': 'JPN',
  'Jordan': 'JOR',
  'Kazakhstan': 'KAZ',
  'Kenya': 'KEN',
  'Kiribati': 'KIR',
  'Korea, Dem. Rep.': 'PRK',
  'Korea, Rep.': 'KOR',
  'Kuwait': 'KWT',
  'Kyrgyz Republic': 'KGZ',
  'Lao PDR': 'LAO',
  'Latvia': 'LVA',
  'Lebanon': 'LBN',
  'Lesotho': 'LSO',
  'Liberia': 'LBR',
  'Libya': 'LBY',
  'Liechtenstein': 'LIE',
  'Lithuania': 'LTU',
  'Luxembourg': 'LUX',
  'Macao': 'MAC',
  'Madagascar': 'MDG',
  'Malawi': 'MWI',
  'Malaysia': 'MYS',
  'Maldives': 'MDV',
  'Mali': 'MLI',
  'Malta': 'MLT',
  'Marshall Islands': 'MHL',
  'Mauritania': 'MRT',
  'Mauritius': 'MUS',
  'Mexico': 'MEX',
  'Moldova': 'MDA',
  'Monaco': 'MCO',
  'Mongolia': 'MNG',
  'Montserrat': 'MSR',
  'Morocco': 'MAR',
  'Mozambique': 'MOZ',
  'Myanmar': 'MMR',
  'Namibia': 'NAM',
  'Nauru': 'NRU',
  'Nepal': 'NPL',
  'Netherlands': 'NLD',
  'New Caledonia': 'NCL',
  'New Zealand': 'NZL',
  'Nicaragua': 'NIC',
  'Niger': 'NER',
  'Nigeria': 'NGA',
  'Norway': 'NOR',
  'Oman': 'OMN',
  'Pakistan': 'PAK',
  'Palau': 'PLW',
  'Panama': 'PAN',
  'Papua New Guinea': 'PNG',
  'Paraguay': 'PRY',
  'Peru': 'PER',
  'Philippines': 'PHL',
  'Poland': 'POL',
  'Portugal': 'PRT',
  'Puerto Rico': 'PRI',
  'Qatar': 'QAT',
  'Romania': 'ROM',
  'Russian Federation': 'RUS',
  'Rwanda': 'RWA',
  'Saudi Arabia': 'SAU',
  'Senegal': 'SEN',
  'Seychelles': 'SYC',
  'Sierra Leone': 'SLE',
  'Singapore': 'SGP',
  'Slovak Republic': 'SVK',
  'Slovenia': 'SVN',
  'Solomon Islands': 'SLB',
  'Somalia': 'SOM',
  'South Africa': 'ZAF',
  'Spain': 'ESP',
  'Sri Lanka': 'LKA',
  'Sudan': 'SDN',
  'Suriname': 'SUR',
  'Sweden': 'SWE',
  'Switzerland': 'CHE',
  'Syrian Arab Republic': 'SYR',
  'Taiwan': 'TWN',
  'Tajikistan': 'TJK',
  'Tanzania': 'TZA',
  'Thailand': 'THA',
  'Togo': 'TGO',
  'Trinidad and Tobago': 'TTO',
  'Tunisia': 'TUN',
  'Turkey': 'TUR',
  'Turkmenistan': 'TKM',
  'Uganda': 'UGA',
  'Ukraine': 'UKR',
  'United Arab Emirates': 'ARE',
  'United Kingdom': 'GBR',
  'United States': 'USA',
  'Uruguay': 'URY',
  'Uzbekistan': 'UZB',
  'Vanuatu': 'VUT',
  'Venezuela': 'VEN',
  'Vietnam': 'VNM',
  'Yemen, Rep.': 'YEM',
  'Zambia': 'ZMB',
  'Zimbabwe': 'ZWE',
};

final List<String> indianStates = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];
